### ISSUE TITLE
Highlights in the gauge are not responding

### ISSUE THREAD

**Issue by WalterColeman** [CodingBSilva/CanvGauge#1]
I am at version 3.1 SR4 of Sense and the highlights are not cooperating. below is what i entered, is there a problem with my script?

"from" : 0, "to" : 1, "color" : "lightgreen" & 'from': 1, 'to' : 2,'color' : 'green'

**Comment by CodingBSilva** [comment]
Hello,

I only have version **3.1 SR3** instaled at the moment, I tested and it works.
On each Highlight box you can have only one sequence like this:
"from" : < tick number >, "to" : < tick number >, "color" : "< color >"

and use " not '

So for your sample you should have:

**1 - Highlights**
"from" : 0, "to" : 1, "color" : "lightgreen"

**2 - Highlights**
"from" : 1, "to" : 2, "color" : "green" 

I know is not elegant but is the only way. I would like to use input masks but I don't know how on Qlik Sense.

Best regards,
Bruno Silva

**Comment by WalterColeman** [comment]
I added as you suggested, can you forward me a sample QVF file that I can try locally?

**Comment by CodingBSilva** [comment]
Hello,

I don't know how to do that :) sorry.
But try using this web file (as measure I have use the Avg([Maximum temperature (°C)])) :
http://www.bom.gov.au/climate/dwo/201605/text/IDCJDW4112.201605.csv

create a new connection select web file. The file header start a 8th position.


LOAD
    "Date",
    "Minimum temperature (°C)",
    "Maximum temperature (°C)",
    "Rainfall (mm)",
    "Evaporation (mm)",
    "Sunshine (hours)",
    "Direction of maximum wind gust ",
    "Speed of maximum wind gust (km/h)",
    "Time of maximum wind gust",
    "9am Temperature (°C)",
    "9am relative humidity (%)",
    "9am cloud amount (oktas)",
    "9am wind direction",
    "9am wind speed (km/h)",
    "9am MSL pressure (hPa)",
    "3pm Temperature (°C)",
    "3pm relative humidity (%)",
    "3pm cloud amount (oktas)",
    "3pm wind direction",
    "3pm wind speed (km/h)",
    "3pm MSL pressure (hPa)"
FROM [lib://Test]
(txt, codepage is 1252, embedded labels, delimiter is ',', msq, header is 8 lines);


I hope it helps.
Best Regards,
Bruno Silva

**Comment by WalterColeman** [comment]
Maybe its because i have 3.1 SR4, but that shouldn't stop it. I must be doing something incorrectly. You might be able to send me a sample by just dragging the sample qvf file in the comment box.

**Comment by CodingBSilva** [comment]
Hello,

I was curious about is happening so i upgrade my Qlik Sense to the 3.1 SR4 version and it works as expected. 
Here is a sample and some printscreens:
[Test.zip](https://github.com/CodingBSilva/CanvGauge/files/731223/Test.zip)
![capture1](https://cloud.githubusercontent.com/assets/16061096/22314400/2b08ed0a-e359-11e6-9cac-2babe298b433.PNG)
![capture2](https://cloud.githubusercontent.com/assets/16061096/22314401/2b0c42fc-e359-11e6-8e3b-fd4a3b1d45bd.PNG)

I hope this helps.
Best regards,
Bruno Silva

**Comment by WalterColeman** [comment]
OK i now see what was happening, my numbers were configured incorrectly. After i adjusted them it worked great. it was my highlight settings: "from" : 0, "to" : 3000, "color" : "red"
i just needed to bump them up

Thank you so much

**Comment by CodingBSilva** [comment]
No problem 👍 

Best regards.

**Comment by WalterColeman** [comment]
is there a way to improve the number formatting and allow  $ and "," or % instead of numeric s?

**Comment by CodingBSilva** [comment]
Hello,
Not at the moment. sorry.
This is based on the Canvas Gauge 1.x I know that there's a new release out but I didn't update this Qlik extension.
You can check the new release on this website (not yet for Qlik Sense):
https://canvas-gauges.com/

Also here some other work on an extension that I would like to release soon (this is just code for fun that's why it takes time to release :) )
![image](https://cloud.githubusercontent.com/assets/16061096/22407364/017df4d8-e65d-11e6-827f-bd0c6f7f94ad.png)
![image](https://cloud.githubusercontent.com/assets/16061096/22407372/22b04eee-e65d-11e6-980a-5edb88eb9697.png)


Best regards,

**Comment by WalterColeman** [comment]
Wow i really like them, i would love to beta test if your willing send me a link to download and i will provide all the feedback

Thank you - Walter

**Comment by CodingBSilva** [comment]
Hello,

At the moment just missing to implement the Areas and Sections :) that are basically very similar to CanvGauge. I was trying to had some Javascript masks or something more clever. But without success.
user will have to write something like this: 0, 25, 'rgba(0, 0, 220, 0.3)'

It is what it is :)

So i Have create the new repository and expected go live date is next Sunday
https://github.com/CodingBSilva/SteelSeries-Canvas-QlikSense

Best regards
